// Code generated by hertz generator. DO NOT EDIT.

package hertz_router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	demoapi "github.com/zhiqinkuang/easy-note/cmd/api/hertz_router/demoapi"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	demoapi.Register(r)
}
